image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/
    - .tox/

before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

test:
  parallel:
    matrix:
      - VERSION: ["3.6", "3.7", "3.8", "3.9", "3.10"]
  image: python:$VERSION
  script:
    - pip install tox
    - tox -e py${VERSION//./},flake8

run:
  script:
    - pip install wheel
    - python setup.py bdist_wheel
  artifacts:
    paths:
      - dist/*.whl
