image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  HATCH_CACHE_DIR: "$CI_PROJECT_DIR/.cache/hatch"

cache:
  paths:
    - .cache/pip
    - .cache/hatch
    - .pytest_cache

before_script:
  - python -V  # Print out python version for debugging
  - pip install hatch

test:
  parallel:
    matrix:
      - VERSION: ["3.6", "3.7", "3.8", "3.9", "3.10", "3.11-rc"]
  image: python:$VERSION
  script:
    - hatch run test:test

run:
  script:
    - hatch build
  artifacts:
    paths:
      - dist
