name: Test

on:
  push:
    branches:
      - master
  pull_request:

env:
  PYTHONUNBUFFERED: "1"

jobs:
  run:
    name: Python ${{ matrix.python }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: ['3.7', '3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}

    - name: Install Hatch
      run: pip install hatch

    - if: matrix.python == '3.11' && runner.os == 'Linux'
      name: Lint
      run: hatch run lint:all

    - name: Test
      run: |
        git config --global user.email "test@idi-systems.com"
        git config --global user.name "IDI Test"
        hatch run full
